name = "m" # Nama proyek Pages Anda
compatibility_date = "2023-11-21"

pages_build_output_dir = "public"

# Ini adalah bagian untuk MENGHUBUNGKAN ke Durable Object yang sudah ada
[[durable_objects.bindings]]
name = "VALIDATORS" # Nama variabel di `env` (env.VALIDATORS)
class_name = "TokenValidator" # Nama kelas di Worker tujuan
script_name = "token-validator-worker" # <-- NAMA WORKER DARI LANGKAH 1