name = "token-access"
compatibility_date = "2024-07-20"

[[durable_objects.bindings]]
name = "TOKEN_STORE"
class_name = "TokenStore"

[build]
command = ""

[[migrations]]
tag = "v1"
new_classes = ["TokenStore"]
