# Nama proyek Anda di Cloudflare
name = "cloudflare-web"

# Memberitahu Cloudflare Pages bahwa file statis (HTML, CSS, JS) ada di direktori root.
pages_build_output_dir = "."

# Tanggal kompatibilitas untuk memastikan API berfungsi seperti yang diharapkan
compatibility_date = "2024-03-20"
#compatibility_flags = ["nodejs_compat"]

# Konfigurasi binding ke KV Namespace Anda
[[kv_namespaces]]
binding = "TOKEN" # Nama variabel yang akan digunakan di dalam Functions
id = "e4b68d7dd477413fbe140f59259254c7" # ID KV Namespace Anda

[[kv_namespaces]]
binding = "ADMIN"
id = "65af14e6ce5f4aad928fc3e474c8642e"

[[kv_namespaces]]
binding = "SIGNAL_STORE"
id = "bfae04f1216a42cab3d602525c423f0f"

[[d1_databases]]
binding = "DB" # Nama variabel yang akan digunakan di kode Worker
database_name = "signals"
database_id = "0c98dba8-35ca-4ba4-a7ae-6fd5617985f4" # <-- GANTI DENGAN ID DATABASE ANDA

